# Generated by Django 3.0.2 on 2020-05-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simple',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='simple',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
