# Generated by Django 3.0.2 on 2020-06-01 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_framework_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='framework',
            old_name='Language',
            new_name='language',
        ),
    ]
